services:
  postgres:
    image: 'postgres:latest'
    container_name: flightdb_container
    restart: always
    environment:
      - 'POSTGRES_DB=flightdb'
      - 'POSTGRES_PASSWORD=kapsas55'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
